# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Filetransfer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46iletransfer.proto\x12\x0c\x66iletransfer\"\x1b\n\x0b\x44\x61taRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1f\n\x0c\x44\x61taResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2V\n\x0c\x46ileTransfer\x12\x46\n\x0bProcessData\x12\x19.filetransfer.DataRequest\x1a\x1a.filetransfer.DataResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Filetransfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=36
  _globals['_DATAREQUEST']._serialized_end=63
  _globals['_DATARESPONSE']._serialized_start=65
  _globals['_DATARESPONSE']._serialized_end=96
  _globals['_FILETRANSFER']._serialized_start=98
  _globals['_FILETRANSFER']._serialized_end=184
# @@protoc_insertion_point(module_scope)
